language: objective-c

osx_image: xcode11
script:

- xcodebuild -workspace CollectionDiffing.xcworkspace -scheme CollectionDiffing -destination 'platform=OS X,arch=x86_64' clean build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  RUN_CLANG_STATIC_ANALYZER=YES
- xcodebuild -workspace CollectionDiffing.xcworkspace -scheme CollectionDiffing clean build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  -destination 'platform=OS X,arch=x86_64' test 
- bash <(curl -s https://codecov.io/bash)


