language: objective-c

osx_image: xcode11
script:

- xcodebuild -workspace CollectionDiffing.xcworkspace -scheme CollectionDiffing clean build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  RUN_CLANG_STATIC_ANALYZER=YES
- xcodebuild -workspace CollectionDiffing.xcworkspace -scheme CollectionDiffing clean build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  test
 
- bash <(curl -s https://codecov.io/bash)


